[package]
name = "numpy-linalg-example"
version = "0.1.0"
authors = ["Yuji Kanagawa <yuji.kngw.80s.revive@gmail.com>"]
edition = "2018"

[lib]
name = "rust_linalg"
crate-type = ["cdylib"]

[dependencies]
numpy = { path = "../.." }
ndarray = ">= 0.13"
ndarray-linalg = { version = "0.12.1", features = ["openblas-static"] }

[dependencies.pyo3]
version = "0.12"
features = ["extension-module"]
