[package]
name = "numpy-linalg-example"
version = "0.1.0"
authors = ["Yuji Kanagawa <yuji.kngw.80s.revive@gmail.com>"]
edition = "2018"

[lib]
name = "rust_linalg"
crate-type = ["cdylib"]

[dependencies]
numpy = { path = "../.." }
ndarray = "0.15"
# ndarray-linalg = { version = "0.13", features = ["openblas-static"] }
ndarray-linalg = { git = "https://github.com/rust-ndarray/ndarray-linalg", features = ["openblas-static"] }

[dependencies.pyo3]
version = "0.15"
features = ["extension-module"]
